# Generated by Django 4.1.7 on 2023-03-30 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_alpha', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('total_emissions', models.FloatField()),
                ('coal', models.FloatField()),
                ('oil', models.FloatField()),
                ('gas_fuel_emissions', models.FloatField()),
                ('cement', models.FloatField()),
                ('flaring', models.FloatField()),
                ('other', models.FloatField()),
                ('per_capita', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissiondataapp.country')),
            ],
        ),
    ]
